[build]
target = "avr-none"
rustflags = [ "-C", "target-cpu=atmega328p"]

[target.'cfg(target_arch = "avr")']
runner = "ravedude uno -cb 57600"

[unstable]
unstable-options = true
build-std = ["core", "alloc"]
